"""reinitial migration

Revision ID: 917d81df3247
Revises: 438905780a27
Create Date: 2024-07-21 18:42:57.621107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917d81df3247'
down_revision = '438905780a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_hashed'), ['hashed'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_hashed'))

    # ### end Alembic commands ###
